swagger: "2.0"
info:
  title: Exo-Scout AI API
  description: API para entrenar modelos de detección de exoplanetas.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /train:
    post:
      summary: Inicia un nuevo trabajo de entrenamiento.
      operationId: trainModel
      x-google-backend:
        address: # Pega aquí la URL de tu ORQUESTRADOR
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: El archivo CSV con los datos.
          required: true
          type: file
        - name: params
          in: formData
          description: Parámetros de entrenamiento en formato JSON string.
          required: true
          type: string
      responses:
        "202":
          description: Petición aceptada.
